# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dylan's Server"
subtitle: "Homer - kainth.tk:49152"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: dark
colors:
  #light:
    #highlight-primary: "#3367d6"
    #highlight-secondary: "#4285f4"
    #highlight-hover: "#5a95f5"
    #background: "#f5f5f5"
    #card-background: "#ffffff"
    #text: "#363636"
    #text-header: "#ffffff"
    #text-title: "#303030"
    #text-subtitle: "#424242"
    #card-shadow: rgba(0, 0, 0, 0.1)
    #link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links

links:
  - name: "Heimdall"
    icon: "fas fa-server"
    url: "https://example.com:49172"
    target: "_blank" # optional html a tag target attribute
  - name: "DashMachine"
    icon: "fas fa-server"
    url: "https://example.com:49161"
    target: "_blank" # optional html a tag target attribute


# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

services:

  - name: "Storage"
    icon: "fas fa-folder"
    items:
     -  name: "Owncloud"
        logo: "assets/icons/owncloud.png"
        subtitle: "Self-Hosted Dropbox Alternative"
        tag: ""
        url: "http://www.kainth.tk:49170"
     -  name: "Plex"
        logo: "assets/icons/plex.png"
        subtitle: "Self-Hosted Media Server"
        tag: ""
        url: "http://www.kainth.tk:49171"
     -  name: "File Explorer"
        logo: "assets/icons/filebrowser.png"
        subtitle: "Server File Explorer"
        tag: ""
        url: "http://www.kainth.tk:49153"
     -  name: "Jupyter"
        logo: "assets/icons/jupyter.png"
        subtitle: "Data Science IDE"
        tag: ""
        url: "https://example.com:49167/"
    #-  name: "Cloud 9"
      # logo: "assets/icons/cloud9.png"
      # subtitle: "Web-Based IDE"
      # tag: ""
      # url: "https://example.com:32773/"

  - name: "Utilities"
    icon: "fas fa-tools"
    items:
        
     -  name: "CyberChef"
        logo: "assets/icons/cyberchef.png"
        subtitle: "The Cyber Swiss Army Knife"
        tag: ""
        url: "http://www.kainth.tk:49159"
        
     -  name: "Theia"
        logo: "assets/icons/theia.svg"
        subtitle: "Visual Studio Code in a browser"
        tag: ""
        url: "https://example.com:49163/"
        
     -  name: "Pyload"
        logo: "assets/icons/pyload.png"
        subtitle: "Python-Based open-source download manager"
        tag: ""
        url: "https://example.com:49158/"
        
     -  name: "Sky"
        logo: "assets/icons/sky.png"
        subtitle: "Router Settings"
        tag: ""
        url: "https://example.com:9012/"
        
     -  name: "Portainer"
        logo: "assets/icons/portainer.png"
        subtitle: "Online Docker Container Manager"
        tag: ""
        url: "http://www.kainth.tk:9000"
        
     -  name: "Transmisisson"
        logo: "assets/icons/transmission.png"
        subtitle: "Free Bittorrent Client"
        tag: ""
        url: "https://example.com:49164"
    
  - name: "Statistics"
    icon: "fas fa-chart-area"
    items:
     -  name: "Netdata"
        logo: "assets/icons/netdata.png"
        subtitle: "Real-Time Server Statistics Viewer"
        tag: ""
        url: "https://example.com:49169/"
    
     -  name: "Grafana"
        logo: "assets/icons/grafana.png"
        subtitle: "All purpose statistics grapher"
        tag: ""
        url: "http://www.kainth.tk:49160"
        
     -  name: "Prometheus"
        logo: "assets/icons/prometheus.png"
        subtitle: "Event monitoring and alerting"
        tag: ""
        url: "http://www.kainth.tk:49155"

     -  name: "Webmin"
        logo: "assets/icons/webmin.png"
        subtitle: "Online UNIX Server Manager"
        tag: ""
        url: "https://kainth.tk:49165"

  - name: "Automation"
    icon: "fas fa-magic"
    items:
     
      - name: "Node-Red"
        logo: "assets/icons/nodered.png"
        subtitle: "IOT Flow Based Development Tool"
        tag: ""
        url: "http://www.kainth.tk:49168"
        
      - name: "n8n.io"
        logo: "assets/icons/n8n.png"
        subtitle: "Web-based Workflow Automation"
        tag: ""
        url: "https://example.com:49166/"
        
  - name: "Minecraft"
    icon: "fas fa-gamepad"
    items:
     -  name: "Dynmap"
        logo: "assets/icons/Dynmap.png"
        subtitle: "Minecraft Dynamic Map"
        tag: ""
        url: "https://example.com:25570"

  - name: "Smart Home"
    icon: "fas fa-home"
    items:
     -  name: "Home Assistant"
        logo: "assets/icons/homeassistant.png"
        subtitle: "Home Automation Platform"
        tag: ""
        url: "https://www.kainth.tk:8123"
     -  name: "Pi-Hole"
        logo: "assets/icons/pihole.png"
        subtitle: "Network Wide Ad-Blocker"
        tag: ""
        url: "http://www.kainth.tk:49173/admin/"
     -  name: "Grocy"
        logo: "assets/icons/grocy.png"
        subtitle: "ERP beyond your fridge"
        tag: ""
        url: "http://www.kainth.tk:49156"
     -  name: "Monica"
        logo: "assets/icons/monica.png"
        subtitle: "Open source personal CRM."
        tag: ""
        url: "http://www.kainth.tk:49157"
        
  - name: "Miscellaneous"
    icon: "fas fa-question-circle"
    items:
      - name: "Ghost"
        logo: "assets/icons/ghost.png"
        subtitle: "Self-Hosted Blog"
        tag: ""
        url: "https://example.com/ghost"
      - name: "Folding@Home"
        logo: "assets/icons/folding.png"
        subtitle: "Protein Fold on your PC"
        tag: ""
        url: "http://www.kainth.tk:49162/"
        
      - name: "jhaals-url"
        logo: "assets/icons/jhaals-url.png"
        subtitle: "Self-Hosted Url Shortener"
        tag: ""
        url: "http://www.kainth.tk:49154"
        
  
